FROM ubuntu:latest
LABEL maintainer="muhaftab@cs.aau.dk"

RUN apt-get update && apt-get -y install cron curl

# Add crontab file in the cron directory
ADD scripts/cronjobs /etc/cron.d/http-cron

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/http-cron

# Apply cron job
RUN crontab /etc/cron.d/http-cron

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log